// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: staticrouter.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteEventType int32

const (
	RouteEventType_ROUTE_EVENT_TYPE_UNSPECIFIED RouteEventType = 0
	RouteEventType_ROUTE_EVENT_TYPE_REPLACE_ALL RouteEventType = 1
)

// Enum value maps for RouteEventType.
var (
	RouteEventType_name = map[int32]string{
		0: "ROUTE_EVENT_TYPE_UNSPECIFIED",
		1: "ROUTE_EVENT_TYPE_REPLACE_ALL",
	}
	RouteEventType_value = map[string]int32{
		"ROUTE_EVENT_TYPE_UNSPECIFIED": 0,
		"ROUTE_EVENT_TYPE_REPLACE_ALL": 1,
	}
)

func (x RouteEventType) Enum() *RouteEventType {
	p := new(RouteEventType)
	*p = x
	return p
}

func (x RouteEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_staticrouter_proto_enumTypes[0].Descriptor()
}

func (RouteEventType) Type() protoreflect.EnumType {
	return &file_staticrouter_proto_enumTypes[0]
}

func (x RouteEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteEventType.Descriptor instead.
func (RouteEventType) EnumDescriptor() ([]byte, []int) {
	return file_staticrouter_proto_rawDescGZIP(), []int{0}
}

type RouteContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	RouteKey      int32                  `protobuf:"varint,3,opt,name=route_key,json=routeKey,proto3" json:"route_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteContext) Reset() {
	*x = RouteContext{}
	mi := &file_staticrouter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteContext) ProtoMessage() {}

func (x *RouteContext) ProtoReflect() protoreflect.Message {
	mi := &file_staticrouter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteContext.ProtoReflect.Descriptor instead.
func (*RouteContext) Descriptor() ([]byte, []int) {
	return file_staticrouter_proto_rawDescGZIP(), []int{0}
}

func (x *RouteContext) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RouteContext) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *RouteContext) GetRouteKey() int32 {
	if x != nil {
		return x.RouteKey
	}
	return 0
}

type RouteRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	RouteKeys     []int32                `protobuf:"varint,3,rep,packed,name=route_keys,json=routeKeys,proto3" json:"route_keys,omitempty"`
	RouteKeyStart int32                  `protobuf:"varint,4,opt,name=route_key_start,json=routeKeyStart,proto3" json:"route_key_start,omitempty"`
	RouteKeyEnd   int32                  `protobuf:"varint,5,opt,name=route_key_end,json=routeKeyEnd,proto3" json:"route_key_end,omitempty"`
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRecord) Reset() {
	*x = RouteRecord{}
	mi := &file_staticrouter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRecord) ProtoMessage() {}

func (x *RouteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_staticrouter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRecord.ProtoReflect.Descriptor instead.
func (*RouteRecord) Descriptor() ([]byte, []int) {
	return file_staticrouter_proto_rawDescGZIP(), []int{1}
}

func (x *RouteRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RouteRecord) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *RouteRecord) GetRouteKeys() []int32 {
	if x != nil {
		return x.RouteKeys
	}
	return nil
}

func (x *RouteRecord) GetRouteKeyStart() int32 {
	if x != nil {
		return x.RouteKeyStart
	}
	return 0
}

func (x *RouteRecord) GetRouteKeyEnd() int32 {
	if x != nil {
		return x.RouteKeyEnd
	}
	return 0
}

func (x *RouteRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RouteSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Routes        []*RouteRecord         `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSnapshot) Reset() {
	*x = RouteSnapshot{}
	mi := &file_staticrouter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSnapshot) ProtoMessage() {}

func (x *RouteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_staticrouter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSnapshot.ProtoReflect.Descriptor instead.
func (*RouteSnapshot) Descriptor() ([]byte, []int) {
	return file_staticrouter_proto_rawDescGZIP(), []int{2}
}

func (x *RouteSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RouteSnapshot) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RouteSnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RouteSnapshot) GetRoutes() []*RouteRecord {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RouteEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=staticrouter.RouteEventType" json:"type,omitempty"`
	Snapshot      *RouteSnapshot         `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEvent) Reset() {
	*x = RouteEvent{}
	mi := &file_staticrouter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEvent) ProtoMessage() {}

func (x *RouteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_staticrouter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEvent.ProtoReflect.Descriptor instead.
func (*RouteEvent) Descriptor() ([]byte, []int) {
	return file_staticrouter_proto_rawDescGZIP(), []int{3}
}

func (x *RouteEvent) GetType() RouteEventType {
	if x != nil {
		return x.Type
	}
	return RouteEventType_ROUTE_EVENT_TYPE_UNSPECIFIED
}

func (x *RouteEvent) GetSnapshot() *RouteSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_staticrouter_proto protoreflect.FileDescriptor

const file_staticrouter_proto_rawDesc = "" +
	"\n" +
	"\x12staticrouter.proto\x12\fstaticrouter\"\\\n" +
	"\fRouteContext\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1b\n" +
	"\troute_key\x18\x03 \x01(\x05R\brouteKey\"\xc4\x02\n" +
	"\vRouteRecord\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1d\n" +
	"\n" +
	"route_keys\x18\x03 \x03(\x05R\trouteKeys\x12&\n" +
	"\x0froute_key_start\x18\x04 \x01(\x05R\rrouteKeyStart\x12\"\n" +
	"\rroute_key_end\x18\x05 \x01(\x05R\vrouteKeyEnd\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x12C\n" +
	"\bmetadata\x18\a \x03(\v2'.staticrouter.RouteRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\rRouteSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x121\n" +
	"\x06routes\x18\x04 \x03(\v2\x19.staticrouter.RouteRecordR\x06routes\"w\n" +
	"\n" +
	"RouteEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.staticrouter.RouteEventTypeR\x04type\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1b.staticrouter.RouteSnapshotR\bsnapshot*T\n" +
	"\x0eRouteEventType\x12 \n" +
	"\x1cROUTE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cROUTE_EVENT_TYPE_REPLACE_ALL\x10\x01B-Z+github.com/wxdqing/staticrouter/model;modelb\x06proto3"

var (
	file_staticrouter_proto_rawDescOnce sync.Once
	file_staticrouter_proto_rawDescData []byte
)

func file_staticrouter_proto_rawDescGZIP() []byte {
	file_staticrouter_proto_rawDescOnce.Do(func() {
		file_staticrouter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staticrouter_proto_rawDesc), len(file_staticrouter_proto_rawDesc)))
	})
	return file_staticrouter_proto_rawDescData
}

var file_staticrouter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staticrouter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_staticrouter_proto_goTypes = []any{
	(RouteEventType)(0),   // 0: staticrouter.RouteEventType
	(*RouteContext)(nil),  // 1: staticrouter.RouteContext
	(*RouteRecord)(nil),   // 2: staticrouter.RouteRecord
	(*RouteSnapshot)(nil), // 3: staticrouter.RouteSnapshot
	(*RouteEvent)(nil),    // 4: staticrouter.RouteEvent
	nil,                   // 5: staticrouter.RouteRecord.MetadataEntry
}
var file_staticrouter_proto_depIdxs = []int32{
	5, // 0: staticrouter.RouteRecord.metadata:type_name -> staticrouter.RouteRecord.MetadataEntry
	2, // 1: staticrouter.RouteSnapshot.routes:type_name -> staticrouter.RouteRecord
	0, // 2: staticrouter.RouteEvent.type:type_name -> staticrouter.RouteEventType
	3, // 3: staticrouter.RouteEvent.snapshot:type_name -> staticrouter.RouteSnapshot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_staticrouter_proto_init() }
func file_staticrouter_proto_init() {
	if File_staticrouter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staticrouter_proto_rawDesc), len(file_staticrouter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staticrouter_proto_goTypes,
		DependencyIndexes: file_staticrouter_proto_depIdxs,
		EnumInfos:         file_staticrouter_proto_enumTypes,
		MessageInfos:      file_staticrouter_proto_msgTypes,
	}.Build()
	File_staticrouter_proto = out.File
	file_staticrouter_proto_goTypes = nil
	file_staticrouter_proto_depIdxs = nil
}
